// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEk5nqTzKNuXgcZmpPisZTDMmhM3UCJEM',
    appId: '1:1082597021869:web:f71b484d968bce2ccd4e24',
    messagingSenderId: '1082597021869',
    projectId: 'flutter-project-hvl289',
    authDomain: 'flutter-project-hvl289.firebaseapp.com',
    storageBucket: 'flutter-project-hvl289.firebasestorage.app',
    measurementId: 'G-NFSTFCND1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEfO-m7wakor2fv3L8wQYXy09kUMJj264',
    appId: '1:1082597021869:android:cc08e7e8e739f89acd4e24',
    messagingSenderId: '1082597021869',
    projectId: 'flutter-project-hvl289',
    storageBucket: 'flutter-project-hvl289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0yZAYffeWKuhrhBCds71uWZE_Ywj7_aQ',
    appId: '1:1082597021869:ios:0685aeda7ccf30f5cd4e24',
    messagingSenderId: '1082597021869',
    projectId: 'flutter-project-hvl289',
    storageBucket: 'flutter-project-hvl289.firebasestorage.app',
    iosBundleId: 'com.ritostore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0yZAYffeWKuhrhBCds71uWZE_Ywj7_aQ',
    appId: '1:1082597021869:ios:0685aeda7ccf30f5cd4e24',
    messagingSenderId: '1082597021869',
    projectId: 'flutter-project-hvl289',
    storageBucket: 'flutter-project-hvl289.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEk5nqTzKNuXgcZmpPisZTDMmhM3UCJEM',
    appId: '1:1082597021869:web:785d8b6ef93e7c6fcd4e24',
    messagingSenderId: '1082597021869',
    projectId: 'flutter-project-hvl289',
    authDomain: 'flutter-project-hvl289.firebaseapp.com',
    storageBucket: 'flutter-project-hvl289.firebasestorage.app',
    measurementId: 'G-0YNJ9Q2N85',
  );
}
